# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Добавляем новые поля в Course
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thematic_tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='categories_tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='attributes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        
        # Добавляем поле is_draft в Trajectory
        migrations.AddField(
            model_name='trajectory',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        
        # Добавляем semester и position в TrajectoryCourse
        migrations.AddField(
            model_name='trajectorycourse',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trajectorycourse',
            name='position',
            field=models.CharField(
                choices=[
                    ('center', 'Центр (обязательный)'),
                    ('top', 'Верх (необязательный)'),
                    ('bottom', 'Низ (необязательный)')
                ],
                default='center',
                max_length=10
            ),
        ),
    ]
